atomist/automation-client

src/tree/TreeNode.ts
src/tree/ast/FileParser.ts
src/tree/ast/FileParserRegistry.ts
src/tree/ast/astUtils.ts
src/tree/ast/microgrammar/MicrogrammarBasedFileParser.ts
src/tree/enrichment.ts
src/tree/path/expressionEngine.ts
src/tree/path/nodeTests.ts
src/tree/path/pathExpression.ts
src/tree/path/pathExpressionParser.ts
src/tree/path/predicates.ts
test/tree/ast/microgrammar/MicrogrammarBasedFileParserTest.ts
test/tree/ast/microgrammar/microgrammarsTest.ts
test/tree/path/expressionEngineTest.ts
test/tree/path/pathExpressionParserTest.ts

First cut of `TreeNode` and path expression support. Based on support in old `rug` project, but simplified due to reduction in scope (no longer needing to handle generic graphs).
Includes integration with microgrammars.
Antlr integration will go in a downstream library because of dependencies.

Added TreeNode and PathExpression support

---

src/internal/common/Flushable.ts
src/operations/generate/SeedDrivenGenerator.ts
src/operations/generate/UniversalSeed.ts
src/operations/generate/java/JavaSeed.ts
src/operations/generate/java/SpringBootSeed.ts
src/operations/generate/java/javaProjectUtils.ts
src/operations/generate/java/updatePom.ts
src/project/File.ts
src/project/Project.ts
src/project/support/AbstractFile.ts
src/project/util/parseUtils.ts
src/project/util/projectUtils.ts
src/tree/ast/FileHits.ts
src/tree/ast/astUtils.ts
test/operations/generate/UniversalSeedTest.ts
test/operations/generate/java/javaProjectUtilsTest.ts
test/operations/generate/java/updatePomTest.ts
test/project/local/LocalProjectTest.ts
test/project/util/parseUtilsTest.ts
test/project/util/projectUtilsTest.ts

Remove `RunOrDefer` and replaced it with simpler `defer` function. Utility methods now return straight promises, but it's still easy to defer (for example, to perform multiple replaces in one operation).
So now `defer(p, p.doThing()` is the opposite of `p.flush()`, enabling us to go in and out of promises at any point.

Exposes promises directly on utility classes, adding defer method

---

package-lock.json
package.json
scripts/atomist-setup.bash
src/atomist-config.ts
src/configuration.ts
src/internal/util/logger.ts
test/atomist.config.ts
test/configurationTest.ts

Add command to create atomist config.  It will prompt for GitHub
credentials and create a GitHub personal access token and write it to
the config.
Add shell script to clone an Atomist API client repo, call
atomist-config, and start up the client, all in one step.  It can be
called from curl.
Add ability to retain simple console log format on CLIs and in tests.

Add atomist-config and atomist-setup

---

src/internal/util/ActionResult.ts
src/operations/common/RepoId.ts
src/operations/common/defaultRepoLoader.ts
src/operations/common/fromProjectList.ts
src/operations/common/gitHubPersisters.ts
src/operations/common/gitHubRepoLoader.ts
src/operations/common/projectPersister.ts
src/operations/common/repoLoader.ts
src/operations/common/repoUtils.ts
src/operations/edit/EditorCommandSupport.ts
src/operations/edit/editAll.ts
src/operations/edit/editModes.ts
src/operations/edit/projectEditor.ts
src/operations/review/ReviewResult.ts
src/operations/review/ReviewerCommandSupport.ts
src/operations/review/projectReviewer.ts
src/operations/review/reviewAll.ts
src/operations/support/contextUtils.ts
src/operations/support/editorUtils.ts
src/project/git/GitCommandGitProject.ts
src/project/git/GitProject.ts
test/operations/edit/LocalEditorTest.ts
test/operations/edit/editAllTest.ts
test/project/git/GitProjectTest.ts

Overhauls editors and reviewers using a more functional approach via functions such as `editAll` and `reviewAll`. The generic `doWithAllRepos` function can be used to run shell-scripts or perform any other cross-repo operation.
Also adds `EditInfo` so editors can pass in whether it uses a branch, PR etc. even down to individual project level.

Overhaul of editing and reviewing

---

src/HandleCommand.ts
src/HandleEvent.ts
src/automationClient.ts
src/configuration.ts
src/onCommand.ts
src/onEvent.ts
src/server/BuildableAutomationServer.ts
src/start.cli.ts
test/internal/invoker/BuildableAutomationServerTest.ts
test/internal/invoker/TestHandlers.ts
test/internal/metadata/functionStyleCommandHandlers.ts

- Added function style event handling and params vs `this` as with command handlers
- Renamed `Handle` function `OnCommand`. Added parallel `OnEvent` function
- Allow investors and event handler classes, as well as factories, to be passed into config

Event handler function and namespace resolution

---

.gitignore
package.json
src/automationClient.ts
src/configuration.ts
src/decorators.ts
src/internal/metadata/decoratorSupport.ts
src/internal/metadata/metadataReading.ts
src/internal/transport/websocket/payloads.ts
src/onCommand.ts
src/scan.ts
src/start.client.ts
test/atomist.config.ts
test/internal/metadata/addAtomistSpringAgent.ts
test/scanTest.ts

This takes away the need to explicitly register handlers. It can be mixed with explicit registeration and can be configured with glob patterns. 
Also fixes issues with functional-style command handlers and metadata.

Scanning for command and event handlers

---

src/spi/message/MessageClient.ts
test/spi/message/MessageClientTest.ts

This takes away the need to create a parameters map via strings. 
Now you can just do:
```
const handler = new HellloWorld();
handler.some_param = "bla";
buttonForCommand({ text: "hello" }, handler);
```
[atomist:enable-auto-merge]

Merge parameters from an instance

---

src/operations/common/repoUtils.ts
src/project/local/NodeFsLocalProject.ts

My editor failed somewhere and the message was "Unable to load repo" which is inaccurate.
Let failures in my editor percolate up.

Don't catch errors in the editor and blame it on the load

---

package-lock.json
package.json
src/tree/ast/typescript/TypeScriptFileParser.ts
test/tree/ast/typescript/TypeScriptFileParserTest.ts

Fixes #77. Also updates `tree-path-ts` version (backward compatible).
Needs more testing, but no reason not to merge at this point as it changes no existing code and adds no dependencies.

Add TypeScript/JavaScript parsing & path expression support

---

src/HandleCommand.ts
src/onCommand.ts
test/command/HelloWorld.ts
test/tree/ast/typescript/typeScriptFileParserProjectTest.ts

Makes `HandleCommand` return `Promise<any | Promise<HandlerResult>`. The union is unnecessary but has value for documentation.
Motivation:
- The status code on `HandleResult` is rarely, if ever, used, vs using `catch`
- Additional data of value on a `HandleResult` instance could just directly come from whatever return type. Note that `handle` methods can carry a type annotation to indicate what they actually promise
- Simple handlers, in particular, are complicated by the need to translate the last promise into a `Promise<HandlerResult>`, when experience has shown that doing that doesn't add much value.
Backward compatible as far as this project is concerned, although technically could break some users (with an easy fix of adding a type annotation to the `handle` method). Most handlers …

Allow HandleCommand to return Promise<any>

---

src/operations/generate/gitHubProjectPersister.ts
test/operations/generate/generatorEndToEndTest.ts
test/operations/generate/universalSeedMetadataTest.ts

another test cleanup pass.
Use different temp repo names so the tests don't interfere with each other.
the univeralmetadataTest is just some error messaging that was usefl, might as well leave it in there

tests pass

---

src/spi/clone/StableDirectoryManager.ts

I used to get errors about "parent directory doesn't exist" when editing multiple projects. This tells it not to delete the whole user directory for each fresh clone, only the repo directory.

fix bug that bothered cloning multiple repos

---

package.json
src/atomist-cli.ts
src/atomist-client.ts
src/atomist-config.ts
src/cli/commands.ts
src/cli/config.ts
src/cli/git-info.ts
src/cli/run.ts
src/git-info.ts
src/start.cli.ts

Move current commands into single CLI.  Organize CLI code into cli
folder.  Disable logging for CLI.  Add help and version command-line
options.  Add compile and install options to start, exiting gracefully
if there is no package.json.

Create a unified atomist CLI

---

test/operations/generate/generatorEndToEndTest.ts

because we don't need to depend on Rod's personal repositories.
He could delete wallaby someday, this is not farfetched

use a repo in atomist-travisorg for testing clone

---

CHANGELOG.md
src/decorators.ts
src/internal/metadata/metadataReading.ts
src/internal/parameterPopulation.ts
src/operations/common/params/SourceRepoParameters.ts
src/operations/common/params/gitHubPatterns.ts
src/operations/generate/AbstractGenerator.ts
src/operations/generate/NewRepoCreationParameters.ts
src/operations/generate/SeedDrivenRepoGenerationParameters.ts
src/operations/generate/generatorUtils.ts
src/operations/generate/gitHubProjectPersister.ts
src/operations/generate/java/JavaSeed.ts
test/internal/invoker/BuildableAutomationServerTest.ts
test/internal/metadata/classWithExternalParametersMetadataReadingTest.ts

Makes it easier to reuse parameters via composition rather than getting into inheritance hell.
- Adds nested parameter supports to all command handlers. Handles parameters, mapped parameters and secrets
- Change `generate` utility method to take a `RepoId` explicitly for flexibility and clarity. Backward compatible.
- Introduces new convenience parameter classes for generators

Fix #34: Add nested parameter support

---

CHANGELOG.md
src/operations/edit/projectEditor.ts
src/operations/edit/projectEditorOps.ts
src/operations/support/editorUtils.ts
test/credentials.ts
test/operations/edit/editAllTest.ts
test/operations/edit/editOneTest.ts
test/operations/edit/projectEditorsOpsTest.ts
test/operations/support/editorUtilsTest.ts
test/project/git/GitProjectTest.ts

Motivation was to fix an error in attempting to commit when git project isn't dirty. This turned into an overhaul of `EditResult.edited` which now has 3 possible values, depending on the editor:
- `false`: Editor says I didn't edit this or don't want you to persist any changes I made
- `true`: Editor says I did edit this, don't bother checking with git
- `undefined`: Editor says I have no idea what I did. Likely to result from wrapping a simple function returning `Promise<Project>`
Paired with @jessitron

Fix error in attempting to commit with git project isn't dirty

---

CHANGELOG.md
src/cli/commands.ts
src/cli/run.ts
src/server/BuildableAutomationServer.ts
src/start.cli.ts
test-api/credentials.ts
test/cli/commandsTest.ts

Using yargs strict likely broke passing parameters to handlers via the
exec CLI command.  This fixes that, also changing parameter
specification to just NAME=VALUE rather than --NAME=VALUE.
Refactor the exec and start commands to share more code and rely less
on exceptions.  Add some tests.
Towards #55

Fix exec command, use name=value parameters

---

src/operations/generate/AbstractGenerator.ts
src/operations/generate/generatorUtils.ts
src/project/git/GitCommandGitProject.ts
src/project/local/NodeFsLocalProject.ts
src/spi/clone/tmpDirectoryManager.ts
test/project/git/CachedGitCloneTest.ts
test/project/git/GitProjectTest.ts
test/project/local/NodeFsLocalProjectTest.ts
test/spi/clone/TmpDirectoryManagerTest.ts

While we're still working on #58 , it's safer to use temporary directories every time than to re-use existing directories without locking.

Safe cloning

---

src/metadata/automationMetadata.ts
src/operations/generate/generatorToCommand.ts
src/server/BuildableAutomationServer.ts
test/internal/invoker/BuildableAutomationServerTest.ts
test/internal/invoker/functionStyleCommandHandlerTest.ts
test/operations/edit/editorHandlerTest.ts

Nested parameters and secrets were not correctly handled. This fixes that and also refines metadata hierarchy to capture commonality between `EventHandlerMetadata` and `CommandHandlerMetadata`.
Paired with @jessitron

Fix nested mapped parameters and secrets handling

---

src/project/git/GitCommandGitProject.ts
src/project/git/gitStatus.ts
test/project/git/CachedGitCloneTest.ts
test/project/git/GitStatusTest.ts

because usually when we ask whether a project is clean we mean, is there something to commit?
I was getting push errors in linting because the only change was in node_modules
this makes status.isClean ignore ignored files, while still storing the ignored file changes, so that my tests can check for whether it's _really_ clean. (also includes the raw output, would have helped with debugging this one)
This is consistent with GitProject.isClean(), which shall now be deprecated.

Separate ignored changes from other changes

---

CHANGELOG.md
src/operations/common/params/SourceRepoParameters.ts
src/operations/generate/UniversalSeed.ts
src/project/fileGlobs.ts
src/project/mem/InMemoryProject.ts
test/project/mem/InMemoryProjectTest.ts

RemoveSeedFiles is neither generic enough nor helpful enough.  It is
easy enough to delete files and directories.
Fix some issues with InMemoryProject file and directory deletions,
including, for example, deleting the file `foobar` if the directory
`foo` was being deleted.  Add tests for deleting files and directories
from InMemoryProject.
AllFiles glob had superfluous `/**`, `**` should be sufficient.

Remove RemoveSeedFiles

---

src/project/git/GitCommandGitProject.ts
test/project/git/CachedGitCloneTest.ts

set the origin to use the token of the user running the current command, regardless of who cloned the repo originally

Reset the token when using an existing clone

---

src/automationClient.ts
src/spi/clone/CachingDirectoryManager.ts
test/project/git/CachedGitCloneTest.ts

This will report about cached clone hits and misses every 10 minutes, both in total and per repo.
I suspect you might want to change the implementation of the "all day" part, the logCachingDirectoryManagerMetricsAllDay method.

Report metrics on clone caching

---

src/automationClient.ts
src/internal/util/metric.ts
src/spi/clone/CachingDirectoryManager.ts
test/project/git/CachedGitCloneTest.ts

This takes @jessitron's changes from #140 and integrates it into the client's metrics infrastructure. 
With this, metrics are available form the metrics endpoint at `http://localhost:2866/metrics`.

re-use existing metrics infrastructure for directory caching

---

CHANGELOG.md
src/operations/common/RepoId.ts
src/project/git/GitCommandGitProject.ts
src/project/local/NodeFsLocalProject.ts
src/spi/clone/CachingDirectoryManager.ts
src/spi/clone/StableDirectoryManager.ts
src/util/gitHub.ts
test/project/git/CachedGitCloneTest.ts

Unify repo creation and move it to gitHub.ts.  Centralize creation of
the clone URL and ensure the token in the clone URL is always viewed
as such by GitHub.
Create directories with fs-extra.ensureDir, it is a lot easier and
more reliable.
Move repo cache to ~/.atomist/cache/repos/github.com/OWNER/REPO.
Closes #63

Fix clone token, unify repo creation, move cache

---

src/action/actionOps.ts
src/internal/transport/AbstractRequestProcessor.ts
src/project/git/GitCommandGitProject.ts
src/project/util/jsonUtils.ts
src/server/BuildableAutomationServer.ts
src/spi/clone/StableDirectoryManager.ts
src/tree/ast/FileHits.ts
src/tree/ast/astUtils.ts
src/tree/ast/typescript/TypeScriptFileParser.ts
test-api/ApolloGraphClientTest.ts
test-api/credentials.ts
test/configurationTest.ts
test/credentials.ts
test/operations/support/editorUtilsTest.ts
test/project/git/GitProjectTest.ts
test/tree/ast/typescript/conversionTests.ts

I noticed tokens were in the test output.  This alarmed me.
Fortunately, Travis CI scrapes the logs and replaces them with
`[secure]`.  Nonetheless, I took the opportunity to remove them by
default, raising the logging level in the tests to "info".  Any higher
and the mocha output is removed.  I also elevated some logs to debug
to quiet the logs even further.  There are still some logs output in
tests.  I left this in as I felt their current level was appropriate.
You can get the verbose logging back by running the tests like this:
```
$ LOG_LEVEL=debug GITHUB_TOKEN=YOUR_TOKEN npm test
```

The Silence of the Tests

---

CHANGELOG.md
src/internal/util/gitHub.ts
src/operations/generate/BaseSeedDrivenGeneratorParameters.ts
src/operations/generate/support/addAtomistWebhook.ts
src/util/gitHub.ts

When generating a project, optionally create a webhook on the repo
with the Atomist webhook URL for that team.  Will add tests for this
functionality when #137 is complete.

Optionally add Atomist webhook to create repo

---

src/operations/common/params/AllReposByDefaultParameters.ts
src/operations/common/params/AlwaysAskRepoParameters.ts
src/operations/common/params/GitHubParams.ts
src/operations/common/params/MappedRepoParameters.ts
src/operations/edit/editAll.ts
src/operations/edit/editorToCommand.ts
src/operations/review/issueRaisingReviewRouter.ts
src/operations/review/reviewerToCommand.ts
src/operations/support/editorUtils.ts
test/operations/edit/editAllTest.ts
test/operations/edit/editOneTest.ts
test/operations/edit/editorHandlerTest.ts

Allows choice of prompting for parameters, using mapped parameters or defaulting to all repos (former behavior of editor and reviewer handler functions.

Overhauled GitHub parameters to allow mapped parameter handling

---

scripts/travis-build.bash

so that we don't have to PR branches before we try them downstream

Build on branches before pull request

---

scripts/travis-build.bash

it didn't build on a branch and now I think we exit when PR is a thing, not when it's false

This condition is backwards?

---

.gitignore
package.json
test-perf/GeneratorBenchmark.ts

It can be run with "npm run benchmark".
There are options to change the number of generator executions, number of files, and amount of file content.
No GitHub usage or tokens are needed. No shell cwd monkeying is required.
Generator source is an in memory project and the target is a local file based project.
I originally wanted to test GenericGenerator, but it does not return a useful result from the generator call that it makes, and it doesn't do anything extra that is relevant. So we are testing the generate method directly so that we can get a useful result back that will tell us the location of the tmp directory where the generated project is.
After the first generator execution we run a basic assert to sanity check that everything worked right, this does not happen on the rest of the …

add generator benchmark test

---

test-api/GitProjectRemoteTest.ts
test-api/editorUtilsWithGitHubPullRequestTest.ts
test-api/generatorEndToEndTest.ts
test-api/gitHubTest.ts
test/credentials.ts
test/operations/review/reviewerHandlerTest.ts
test/operations/support/editorUtilsTest.ts
test/project/git/GitProjectTest.ts

Changing these test to use mocks will take more work and may invalidate them.
there is still some interaction with GitHub in the unit tests that could be removed. But for now, any string without whitespace can be used as a token.

move tests that expect a legitimate GitHub token to test-api

---

CHANGELOG.md
src/scan.ts

Most projects do not have the handlers directory, using src/commands and
src/events instead.  Remove "handlers/" from the glob pattern to
scanning works either way.

Remove handlers from scan glob

---

package.json
src/action/actionOps.ts
src/operations/common/AbstractRemoteRepoRef.ts
src/operations/common/GitHubRepoRef.ts
src/operations/common/RemoteFactory.ts
src/operations/common/RepoId.ts
src/operations/generate/GenericGenerator.ts
src/operations/generate/generatorToCommand.ts
src/operations/generate/gitHubProjectPersister.ts
src/operations/generate/remoteGitProjectPersister.ts
test/api/generatorEndToEndTest.ts
test/bitbucket-api/BitBucketGitTest.ts
test/operations/generate/generatorToCommandTest.ts

- Introduce `deleteRemote` method and implement for GitHub for consistency
- Add BitBucket generation support
- Rename `githubProjectPersister` `gitRemoteProjectPersister` while preserving backward compatibility
- Project persister no longer GitHub specific
- Remove code duplication in header creation in `GitHubRepoRef`
- Suppress console output
Please preserve commit history.

Add BitBucket generation support to generate function

---

src/operations/common/params/BaseEditorOrReviewerParameters.ts
src/operations/common/params/GitHubTargetsParams.ts
src/operations/common/params/TargetsParams.ts
src/operations/edit/editorToCommand.ts
src/operations/review/issueRaisingReviewRouter.ts
src/operations/review/reviewerToCommand.ts
src/operations/tagger/taggerHandler.ts

Decouples reviewer and editor command support from GitHub.

Hide ProjectOperationCredentials type in GitHubTargetsParams

---

CHANGELOG.md
src/internal/env/gitInfo.ts
test/internal/env/gitInfoTest.ts

Gracefully handle non-Git repositories when determining Git
information.  Rather that rely on git binary, extract Git information
directly.
Resolves #131

Handle non-git automation clients

---

src/operations/common/params/Credentialed.ts
src/operations/common/params/TargetsParams.ts
src/operations/generate/NewRepoCreationParameters.ts
src/operations/generate/generatorToCommand.ts

Tiny PR to hide ProjectOperationCredentials in generation

---

src/operations/common/params/GitHubSourceRepoParameters.ts
src/operations/common/params/SourceRepoParameters.ts
src/operations/generate/BaseSeedDrivenGeneratorParameters.ts
src/operations/generate/GitHubRepoCreationParameters.ts
src/operations/generate/NewRepoCreationParameters.ts
src/operations/generate/support/addAtomistWebhook.ts
test/api/generatorEndToEndTest.ts
test/operations/generate/generatorToCommandTest.ts

Backward compatible. Makes it possible to generate using BitBucket or GHE by pushing GitHub mapped parameters down into subclasses.
Have tested this build with `spring-automations` to verify it still works via Slack.

Decouple generator parameters from GitHub.com

---

package-lock.json
package.json
src/graph/ApolloGraphClient.ts
src/graph/graphQL.ts
test/graph/GraphQLTest.ts
test/graph/someSubscription.graphql

This allows to specify the usage of parameters when using `GraqhQL.subscriptionFromFile(path, current, parameters))`
eg. the following graphql file has three parameters:
```
subscription SomeSubscription {
ChatTeam(id: $teamId) {
orgs {
repo(first: 100, offset: $offset, private: $isPrivate) {
owner
name
}
}
}
}
```
When using this with
```
const query = GraphQL.subscriptionFromFile(
"./someSubscription",
__dirname,
{
teamId: "T1L0VDKJP",
offset: 100,
isPrivate: true,
});
```
the variables get replaced in the predicates.
NOTE: this doesn't give you full support for variables in subscriptions right now but we don't offer that in the API anyway as of today. This is a good first step.

Subscription parameters

---

src/project/util/jsonUtils.ts
test/project/util/jsonUtilsTest.ts

the generator rewrote my json with 0 spacing, because it had a newline at the end of the file so it didn't recognize the spacing of 2.
This defaults to 2 instead of 0, and also removes and replaces newlines when looking for spacing, so as not to change that.

handle newline in json

---

src/operations/edit/editModes.ts
src/operations/support/editorUtils.ts

This is useful, for example, to be able to set a GitHub status on a new branch.

Added beforePersist and afterPersist hooks to EditMode

---

src/operations/common/AbstractRemoteRepoRef.ts
src/operations/common/GitHubRepoRef.ts
src/operations/common/RepoId.ts
src/operations/common/params/gitHubPatterns.ts
src/operations/support/editorUtils.ts
test/configurationTest.ts
test/operations/common/GitHubRepoRefTest.ts

We often want to specify both this and the SHA
especially for editors; they must have a branch. and statuses must have a sha.

Add branch as an optional field to RepoRef

---

src/internal/transport/express/ExpressServer.ts

we can work around this by sending `"command": handlerName` in the post data

make it work like get because get works

---

src/automationClient.ts
src/configuration.ts

In its current location, the debug statement printing the client
configuration did not work because the log level was defaulted to info
and was not being changed until after the statement.  Rather than
change the statement to info level as I had previously done, I move
the statement to the client run() method where it will be printed if
the logging level dictates it.

Move config debug statement to run

---

CHANGELOG.md
src/atomist-cli.ts
src/atomist-client.ts
src/atomist-config.ts
src/git-info.ts

Remove the deprecated command-line utilities superseded by the
combined `atomist` CLI.

Remove previously deprecate CLIs

---

CHANGELOG.md
src/cli/commands.ts

The Node.js executable is named `node.exe` on MS Windows.  On win32
bin scripts are installed as wrappers, not symlinks.  Use the .cmd
wrapper directly rather than trying to figure out the correct
multi-platform node incantation.  Improve abstractions and diagnostics
around command failure.
Clean up path/cwd confusion.
Towards #271 
Tested on a Windows 10 dev VM.

Better command invocation on win32

---

src/automationClient.ts
src/configuration.ts
src/decorators.ts
src/index.ts
src/internal/metadata/decoratorSupport.ts
src/internal/metadata/metadataReading.ts
src/internal/parameterPopulation.ts
src/metadata/automationMetadata.ts
src/onCommand.ts
src/server/BuildableAutomationServer.ts
test/atomist.config.ts
test/command/HelloWorld.ts
test/configurationTest.ts
test/event/HelloIssue.ts
test/internal/invoker/functionStyleCommandHandlerTest.ts
test/internal/metadata/addAtomistSpringAgent.ts
test/internal/metadata/classStyleMetadataReadingTest.ts
test/internal/metadata/eventMetadataReadingTest.ts
test/internal/metadata/functionStyleMetadataReadingTest.ts
test/scanTest.ts

This allows us to inject values from the configuration object into command and/or event handlers. 
As an example:
```
interface DockerOptions {
registry: string;
user: string;
password: string;
}
... 
@Value({ path: "docker", root: "custom", required: false })
public dockerOptions: DockerOptions;
```
with the following configuration: 
```
export const configuration: Configuration = {
custom: {
docker: {
registry: "http://google.com",
user: "something",
password: "something else",
},
},
};
```
If access to configuration is needed from outside command or event handlers, there is now the following method: 
```
const dockerOptions = configurationValue<DockerOptions>("custom.docker");
```

Support for injection of configuration values

---

CHANGELOG.md
src/cli/commands.ts
src/start.cli.ts

Rather than default to true, install will only be run if
its expected outputs, the node_modules, does not exist.
If the option or its negation is provided, the existence
of the output directory is immaterial.

Change default behavior for --install

---

CHANGELOG.md
src/cli/config.ts
src/configuration.ts

To aid transition from environment variables to custom configuration,
a more secure solution, have `atomist config` probe for known SDM
environment variables and store them in the custom property of the
user configuration.
This will always prompt for team when `atomist config` is run.

Save SDM env vars to user config

---

src/project/git/GitCommandGitProject.ts
src/project/git/GitProject.ts
test/project/git/GitCommandGitProjectTest.ts

Allow --follow-tags, --force, --force-with-lease, --quiet, and
--verbose options.
Towards atomist/sdm#378

Add options to GitProject.push()

---

package-lock.json
package.json
src/automationClient.ts
src/configuration.ts
src/graph/graphQL.ts
src/index.ts
src/ingesters.ts
src/internal/graph/graphQL.ts
src/server/BuildableAutomationServer.ts
test/atomist.config.ts
test/graphql/ingester/helloWorld.graphql
test/graphql/ingester/sdmGoal.graphql
test/ingestersTest.ts

This adds support for defining ingesters in GraphQL SDL format. By
convention those SDL files should have a graphql extension and
should be placed inside the graphql/ingester folder.
fixes #281

Add support for SDL ingesters

---

src/cli/config.ts

because that's what it's called on the dashboard

Ask for a workspace ID

---

src/internal/util/logger.ts

While we may want all clients that use the logger to send the console.log to the logger by default, sometimes we don't.
In particular, a local SDM has a CLI, and yargs writes usage information to console.log. 
This lets programs which load this file restore the original console.log if they choose. And also reroute through the logger later in case they want to do that.

Allow local sdm to restore console methods

---

package-lock.json
src/operations/common/BitBucketServerRepoRef.ts
src/util/spawned.ts

This is to bypass some serious trickiness with client certs
Define ATOMIST_CURL_FOR_BITBUCKET to nonempty to get the curl behavior.
I had to move spawnAndWatch to client, which I think we wanted to anyway.
This should require no changes to sdm except an upgrade of client, but I'll make a PR there that delegates to the client's spawnAndWatch to remove duplication.

Sometimes we want to use curl to talk to BitBucket

---

CHANGELOG.md
src/operations/edit/projectEditor.ts
src/project/Project.ts
src/project/util/parseUtils.ts
src/project/util/projectUtils.ts
src/tree/ast/FileHits.ts
src/tree/ast/astUtils.ts
test/project/local/NodeFsLocalProjectTest.ts
test/project/util/parseUtilsTest.ts
test/project/utils.ts

`Project` interface no longer extends `ScriptedFlushable`, as this model is no longer necessary with async/await. Implementation does not change, but these details are hidden.

API simplification

---

src/configuration.ts
src/spi/http/axiosHttpClient.ts
src/spi/http/curlHttpClient.ts
src/spi/http/httpClient.ts
src/util/retry.ts
test/configurationTest.ts
test/spi/http/axiosHttpClientTest.ts
test/spi/http/curlHttpClientTest.ts

This provides new `HttpClient` and `HttpClientFactory` interfaces. The latter can get registered on `configuration.http.client.factory` and overwrite the default of `AxiosHttpClientFactory`. 
I provided a `curl`-based implementation.

HTTP client and factory abstraction

---

package-lock.json
src/ingesters.ts

When Configuration contains a class with private/protected fields, at any level,
then a Configuration that resolves to one installation of automation-client
is _never_ the same type that resolves to a Configuration that resolves o
another installation, even if they're the same version, if they're in different
spots on the filesystem. TypeScript protects us. :-/
So don't do it. It's better to never require a class, but only an interface.
Right now I want to see if this will get us around the problem.

Work around 'Type ... is not assignable to type Configuration'

---

src/ingesters.ts

here's another one.
I don't know why it didn't show up in my testing earlier, but it's biting me now.
If this weren't deprecated I'd hide the class behind an interface instead, but that's more work

Work around Type ... is not assignable to type Configuration'

---

src/start.command.ts

The current run.ts does not work with automation clients that rely on
scanning for command handlers.  Rather than fix that script, which
resides in the now deprecated cli subdirectory, I created
start.command.ts for two reasons.  First, it is easier to determine if
an automation client has a working script to run command handlers, it
is just a check for a file rather than having to parse it.  Second,
the new name parallels the start.client.ts script.

Replace run.ts with start.command.ts

---

src/internal/transport/AbstractRequestProcessor.ts

This was failing with TypeError in the response to /events.
It resulted in a socket hang up.
You may have a better way to defend against this.

Do not send circular JSON back from event handlers

---

src/bin/command.ts
src/bin/git-info.ts
src/bin/gql-gen.ts
src/bin/start.ts

Move scripts to a bin directory.  This is standard for Node.js
packages.  Unlike most Node.js packages, these scripts are in src/bin
rather than bin, but with the rearrangement on packaging, they will
end up in bin and, should this project ever get rearranged to be more
standard, the location of the bin will not change.

Move scripts to bin directory

---

src/internal/transport/express/ExpressServer.ts
src/server/AbstractAutomationServer.ts

Then I am trying to make sdm-local treat 404 as OK from this endpoint; it's OK if there are no handlers

If no event handlers are found, return 404 not 500

---

src/util/statsd.ts

Hi @cdupuis -- I've just been trying to sort out our biggest metrics today.
Some of these ones reported more than 15,000 in the last hour due to the combination of all the dimensions present.
This is my suggestion for what would be great to cut down the metric use but I'm not sure how much these are used and how important they are to you.
Removing team based dimensions is usually the most important thing - that and not have multiple changeable dimensions (tags) on one metric.
I've left all the dimensions on the failure metrics as they don't occur a lot and are probably the most important.
Let me know what you think. I've been through this process for the backend services now.

Remove dimensions on metrics

---

src/index.ts
src/spi/message/MessageClient.ts

Export from the index all exports from MessageClient.  Add TypeDoc to
help make inputs and returns more clear.  Rename "rug" functions to
"chat".

Export all of MessageClient

---

src/spi/clone/DirectoryManager.ts

It's checking the branch and using --branch to get whichever one, in clone

Match comment to code

---

src/operations/common/AbstractRemoteRepoRef.ts

It's better than 'Cannot read property 'username' of undefined' which is what I was getting
and I think this is a better place to throw than isBasicAuthCredentials

Throw a particular error if credentials do not exist

---

package-lock.json
package.json
src/tree/LocatedTreeNode.ts
src/tree/ast/FileHits.ts
src/tree/ast/FileParser.ts
src/tree/ast/FileParserRegistry.ts
src/tree/ast/astUtils.ts
src/tree/ast/microgrammar/MicrogrammarBasedFileParser.ts
src/tree/ast/typescript/TypeScriptFileParser.ts
test/tree/ast/microgrammar/MicrogrammarBasedFileParserTest.ts
test/tree/ast/typescript/TypeScriptFileParserTest.ts
test/tree/ast/typescript/conversionTests.ts

Upgraded `tree-path` library to benefit from a bug fix in handling tree node attribute tests. However, it turned out that the version of `tree-path` used was very old and upgrading necessitated extensive import changes (which are all improvements, being from the index).
No change to actual implementation of `automation-client`.

Upgrade tree-path library

---

lib/configuration.ts
test/configurationTest.ts

Use os.homedir() to determine home directory.  Use 127.0.0.1 rather than
localhost as it is more reliable.

Use os.homedir() and 127.0.0.1

---

index.ts
lib/util/spawn.ts

So we can have a common spawn and exec to run from SDMs/clients.

Export cross-spawn as spawn

---

index.ts

Remove exports from the index that are only used by our internal
libraries, leaving the index as the definition of the
automation-client public interface.
Closes #391

Remove non-SDM exports from index

---

bin/gql-gen.ts

Do not include ingester specifications from GraphQL type generation.
This change also fixes the location of the `graphql` subdirectory to
directly under the `lib` or `src` directory.  This is a change, but
likely not breaking as the location of a project-specific schema.json
was already limited to `{lib,src}/graphql`.

Exclude ingesters from gql-gen

---

index.ts
lib/operations/review/ReviewResult.ts
test/operations/review/ReviewResult.test.ts

Generally useful function suitable for use by Array.prototype.sort()
to sort review comments by severity, category, subcategory, and
location.

Add review comment sorter

---

index.ts
lib/configuration.ts
lib/internal/transport/websocket/WebSocketClient.ts
lib/internal/util/string.ts
lib/onCommand.ts
lib/spi/http/axiosHttpClient.ts
lib/spi/http/httpClient.ts
lib/spi/http/wsClient.ts
lib/util/retry.ts
test/configuration.test.ts

With this change, HTTP and WS client can be configured correctly to work
in all sorts of network situations, like tunnelling proxies.

Extract creation of HTTP and WS clients for registration to proper factories

---

lib/configuration.ts
lib/graph/ApolloGraphClient.ts
lib/graph/ApolloGraphClientFactory.ts
lib/internal/transport/RequestProcessor.ts
lib/internal/transport/cluster/ClusterWorkerRequestProcessor.ts
lib/internal/transport/express/ExpressRequestProcessor.ts
lib/internal/transport/websocket/DefaultWebSocketRequestProcessor.ts
lib/spi/graph/GraphClientFactory.ts
lib/spi/http/axiosHttpClient.ts
lib/spi/http/httpClient.ts
test/command/HelloWorld.ts
test/configuration.test.ts
test/internal/transport/AbstractRequestProcessor.test.ts
test/internal/transport/websocket/DefaultWebSocketTransportEventHandler.test.ts

This allows to modify the creation of `GraphClient` instances through a factory. 
The default implementation `ApolloGraphClientFactory` allows to plug in strategies to modify the internally used fetch instance.

Add `GraphClientFactory`

---

lib/operations/common/GitlabRepoRef.ts
lib/operations/edit/editModes.ts
lib/operations/support/editorUtils.ts
lib/project/git/GitProject.ts

Adding the missing `Commit` edit mode instead of creating a `BranchCommit` manually. This is better for code completion.
Added support for target branch to `PullRequest`. Pass the `targetBranch` to the underlying PR creation functions in the repo refs.
Also fixed the calls to `HttpClientFactory.create` in the Gitlab support to pass the URL.

Introduce Commit editMode and allow PR to specify base

---

lib/internal/transport/cluster/ClusterMasterRequestProcessor.ts
lib/internal/transport/websocket/DefaultWebSocketRequestProcessor.ts
lib/internal/transport/websocket/WebSocketLifecycle.ts
lib/operations/common/params/AlwaysAskRepoParameters.ts
lib/operations/common/params/GitHubFallbackReposParameters.ts
lib/operations/common/params/GitHubTargetsParams.ts
lib/operations/common/params/GitlabTargetsParams.ts
lib/operations/common/params/MappedRepoParameters.ts
lib/operations/common/params/TargetsParams.ts
lib/operations/edit/editModes.ts
lib/operations/generate/generatorUtils.ts
test/operations/generate/generatorUtils.test.ts

Introduce `targets.branch` to instruct a `CodeTransform` to work off of a branch.
Fix `project.id` as 1st parameter to a `CodeTransform` to always point to the correct repo; and not - in the case of project creation - to the local cloned seed repo.
Removed default to merge into `master` for `PullRequest` edit mode.

Introduce `targets.branch` and fix `project.id` to point to correct project

---

lib/project/util/projectUtils.ts
lib/tree/ast/FileParser.ts
lib/tree/ast/astUtils.ts
test/project/util/projectUtils.test.ts
test/tree/ast/astUtils.test.ts

Optimize, determining whether a file needs to be parsed based on literal value tests using string searches before invoking an actual FileParser.
When using expensive parsers such as ANTLR, this can increase performance by many times greatly reducing the number of files that need to be parsed.
Also add an optional method FileParser implementations can implement to provide further optimization.
Also adds async generator functions for project and AST operations. These can be more performant when we don't need all results, and when parsing is CPU bound so that parallel promise execution won't work.

Performance optimization for AST parsing

---

lib/tree/ast/astUtils.ts
test/tree/ast/astUtils.test.ts

`matchIterator` can now be used to change matches, even if a caller jumps out of the generator while iterating.
Also slight refactoring to use async/await.

Allow matchIterator to be used to change matches

---

index.ts
lib/tree/ast/astUtils.ts
lib/tree/ast/matchTesters.ts
test/tree/ast/microgrammar/microgrammars.test.ts

Newer path expression functions now allow the use of a "match tester," which allows some matches to be excluded. This allows contextual decision making, as in using the new `notWithin` function to excluded matches within another type of match.
The following test shows usage and its effect:
```typescript
it("should exclude with notWithin MatchTester", async () => {
const mg = Microgrammar.fromString<Person>("${name}:${age}", {
age: Integer,
});
const file = Microgrammar.fromDefinitions<{ first: Person, second: Person }>({
first: mg,
second: mg,
});
const parseWith = new MicrogrammarBasedFileParser("people", "pair", file);
const p = InMemoryProject.of(
{ path: "Thing1", content: "Tom:16 Mary:25" },
{ path: "Thing2", content: "George:16 Kathy:25" },
);
const it = matchIterator(p, { …
```

Add support for contextual suppression of matches using path expressions

---

package-lock.json
package.json
test/tree/ast/microgrammar/MicrogrammarBasedFileParser.test.ts
test/tree/ast/microgrammar/microgrammars.test.ts

the goal is to get to microgrammar 1.0.3, with no 1.0.1 on the path, so that
we can allow SDMs to upgrade. 1.0.3 has a fix to remove Concat (class with
a private field) from the Microgrammar type, so that there isn't a conflict
between minor versions of the Microgrammar type.
Until then we get compile errors on any version of Microgrammar except precisely the one client uses.

Upgrade tree-path and microgrammar

---

index.ts
lib/tree/ast/microgrammar/MicrogrammarBasedFileParser.ts
lib/tree/ast/regex/RegexFileParser.ts
test/tree/ast/regex/RegexFileParser.test.ts

Similar to microgrammar based parsers, make it possible to match and destructure regular expression groups using path expressions. For example:
```typescript
const personParser = new RegexFileParser({
rootName: "people",
matchName: "person",
regex: /([A-z][a-z]+):([\d]+)/,
captureGroupNames: ["name", "age"],
});
const matches = await findMatches<Person>(p, personParser, AllFiles, "/people/person/name");
```

Allow path expressions to be backed by regular expressions with capture groups

---

lib/operations/generate/remoteGitProjectPersister.ts
test/api/generatorEndToEnd.test.ts

Prior to this commit their was always a message that said 'Probably
exists' when a new repo failed to create from a generator.  This was
misleading when the errors where coming from something like an
authorization problem (401).  Updated to make it more generic and let
the `err` object provide the detail.

Update failure logging for failed repo creations

---

lib/internal/invoker/disposable.ts

We combined the strings so much that a few projects ran into InvalidStringLength and crashed.
This is extra funny because it was building a string
"inconceivable and inconceivable and inconceivable  and inconceivable and inconceivable and inconceivable and inconceivable and inconceivable and inconceivable and inconceivable and inconceivable and inconceivable and inconceivable and inconceivable and inconceivable and inconceivable and inconceivable and inconceivable and inconceivable and inconceivable and inconceivable and inconceivable and inconceivable and inconceivable and inconceivable and inconceivable and inconceivable and inconceivable and inconceivable and inconceivable and inconceivable..."

Fix typo that crashed it

---

lib/project/File.ts
lib/project/local/NodeFsLocalFile.ts
lib/project/mem/InMemoryFile.ts
lib/project/support/AbstractFile.ts

this gives us an abstraction that makes uploads to S3 work.

Add getContentBuffer method to File

---

lib/internal/transport/websocket/WebSocketLifecycle.ts
test/internal/transport/websocket/WebSocketMessageClient.test.ts
test/operations/support/editorUtils.test.ts

There were unhandled promise exceptions in the test because tests were
creating a websocket that never was connected and so was unable to
send messages.  The interval function kept running after the websocket
was destroyed, causing `this` to become undefined.  Since this could
also adversely affect normal operation, I added a check to ensure
`this` was defined.
Changes in the tests are whitespace and increasing the timeout on some
recently temperamental tests.

WebSocket can be destroyed before message sent

---

bin/gql-gen.ts
package-lock.json

Add tslint:disable comment to top of generated types file.  Make
things more async.  Only patch GraphQL TypeScript template if
generating types.
Closes #481

Disable TSLint on generated types

---

index.ts
lib/operations/common/AbstractRemoteRepoRef.ts
lib/util/logger.ts
package-lock.json
test/util/logger.test.ts

So, while streaming, I noticed that my token was printing to the log when the SDM clones a repository. This is because the token gets sent on the command line, and we always print to the logs the commands that we run from exec/spawn. I like that we print those, but I don't want the tokens to show.
After some discussion with @johnsonr, I implemented a variant of what TeamCity does, which is to have some awareness of what passwords look like and redact them from the logs. In this case, the file that constructs the clone URL with tokens in it also asks the logger (globally) to suppress anything that looks like those tokens. This is a good idea.
This is not intended to be a complete solution of all password not-printing everywhere. It is general enough to cover the cases we know exist. This …

Suppress token when logging clone url

---

index.ts
lib/internal/transport/cluster/ClusterMasterRequestProcessor.ts
lib/internal/transport/websocket/WebSocketLifecycle.ts
lib/operations/common/AbstractRemoteRepoRef.ts
lib/operations/common/BitBucketRepoRef.ts
lib/operations/common/BitBucketServerRepoRef.ts
lib/operations/common/GitHubRepoRef.ts
lib/operations/common/GitlabRepoRef.ts
lib/operations/common/RepoId.ts
lib/operations/common/remoteRepoRef.ts
test/util/logger.test.ts

Each RemoteRemoteRef implementation has slightly different ways they
are created.  Add a single function with an object parameter to unify
creation of the various RemoteRepoRefs.
Export the new function and the missing BitBucketRepoRef and
ProviderType as ScmProviderType from the index.
Delint and fix token redacting and some tests.

Create single interface for creating RemoteRepoRef

---

index.ts
lib/automationClient.ts
lib/configuration.ts
lib/internal/transport/cluster/ClusterMasterRequestProcessor.ts
lib/internal/transport/express/ExpressRequestProcessor.ts
lib/internal/transport/websocket/DefaultWebSocketRequestProcessor.ts
lib/internal/transport/websocket/WebSocketMessageClient.ts
lib/operations/common/AbstractRemoteRepoRef.ts
lib/util/logger.ts
lib/util/redact.ts
test/command/HelloWorld.ts
test/configuration.test.ts
test/internal/transport/websocket/WebSocketMessageClient.test.ts
test/util/redact.test.ts

Lets users configure redaction patterns and possible replacements in the configuration. Can be used to redact log and messages send via the message client.
By defaults installs redactions to hide GitHub tokens and user/passwords in urls.
fixes #526

Redact outgoing messages

---

lib/automationClient.ts
lib/configuration.ts
lib/internal/env/applicationEvent.ts
lib/internal/transport/cluster/ClusterMasterRequestProcessor.ts
lib/internal/transport/cluster/ClusterWorkerRequestProcessor.ts
lib/internal/transport/websocket/DefaultWebSocketRequestProcessor.ts
lib/internal/transport/websocket/WebSocketClient.ts
lib/internal/util/poll.ts
lib/internal/util/shutdown.ts
lib/spi/clone/StableDirectoryManager.ts
lib/spi/statsd/statsd.ts
test/action/actionChaining.test.ts
test/util/child_process.test.ts

The master organizes shutdown of a cluster, waiting for the queue to
empty and telling the workers to shutdown.  If the workers receive a
shutdown signal, they check and potentially wait to see if the master
has sent them a shutdown message.  If not, they shutdown anyway but at
least give themselves some time to complete work.  Configure max
shutdown timeout based on configured grace period.  Execute all
shutdown hooks, even if some throw an error.
Provide helper functions for graceful termination.  Add graceful
functionality to non-cluster mode.
If not shutting down, replace any worker that exits, regardless of
how.
Provide a sleep function.
Delint files I touched.
Towards #543
Maybe `termination` should be a top-level configuration property.

Rework cluster shutdown

---

index.ts
lib/globals.ts
lib/internal/transport/cluster/ClusterMasterRequestProcessor.ts
lib/internal/transport/cluster/messages.ts
lib/internal/transport/websocket/WebSocketClient.ts
lib/internal/util/shutdown.ts

Provide a means to process async shutdown hooks while returning a
specific exit status.  This is potentially breaking if user-provided
shutdown hooks using the default priority require that they execute
after the websocket is closed, which seems very unlikely.

Allow for normal exit with async hooks

---

lib/operations/common/BitBucketServerRepoRef.ts

Query params were not being passed when retrieving Bitbucket default reviewers. Resulting error would be:
```
{"errors":[{"context":null,"message":"A sourceId is required when getting reviewers.","exceptionName":"com.atlassian.bitbucket.validation.ArgumentValidationException"}]}
```

Ensure query params are passed when retrieving default reviewers

---

lib/configuration.ts
test/asyncConfig.ts
test/configuration.test.ts

This makes creating `export const configuration` more flexible as it now come from an async method invocation.

Allow configuration to be a `Promise<Configuration>`

---

lib/project/git/GitCommandGitProject.ts
lib/spi/clone/DirectoryManager.ts
test/project/git/CachedGitClone.test.ts

This is for org-visualizer, it wants to count branches but not fetch them deeply

Add a clone option to shallowly fetch all branches

---

bin/start-dev.ts
lib/internal/transport/showStartupMessages.ts
package-lock.json
package.json

This adds a different `start-dev.js` script to the bin directory that starts the automation-client in a mode that reloads changes in the user code when there are changes to js files detected. 
As long as the user doesn't change metadata that would require a new registration to be made with the API, the changes are reloaded. If there are metadata changes (like changing the intent of a command handler) a diff is printed and the process exists.
This has no impact on running an automation-client with the current `start.js` script.
A corresponding PR on the atomist/cli will add a new `--dev` flag to `atomist start`.
Big thanks to @XertroV for the inspiration and some of the initial code.

Add support for code reloading without restart

---

lib/project/File.ts
lib/project/HasCache.ts
lib/project/Project.ts
lib/project/fileGlobs.ts
lib/project/local/NodeFsLocalProject.ts
lib/project/mem/InMemoryProject.ts
lib/project/support/AbstractFile.ts
lib/project/support/AbstractProject.ts
lib/project/util/projectUtils.ts
lib/tree/ast/FileHits.ts
lib/tree/ast/astUtils.ts
package-lock.json
package.json
test/project/local/NodeFsLocalProject.test.ts
test/project/mem/InMemoryProject.test.ts
test/project/perf/diskPerformance.test.ts
test/project/util/parseUtils.test.ts
test/project/util/projectUtils.test.ts
test/tree/ast/typescript/TypeScriptFileParser.test.ts
test/tree/ast/typescript/javaScriptFileParserProject.test.ts
test/tree/ast/typescript/typeScriptFileParserProject.test.ts

Makes project operations significantly faster.
- Caches file paths in `Project` to make successive glob and file searches much faster. This is available via the new `getFiles` method.
- Make `projectUtils` use the new method.
- Introduces user `cache` property in `Project` and `File` allowing expensive computations to be stored in a `Project` instance during its lifetime.
- Change `astUtils` to cache the AST for each parser by default.
- Add disk performance benchmark tests, skipped by default.
Also deprecates some `astUtils` functions, adding new functions that take an options object rather than individual parameters.
*Needs further testing before merging* (@lievendoclo), as well as review.
*DO NOT MERGE until further investigation. There may be a bug shown in aspect-sdm*

Introduce caching to Project API

---

lib/internal/transport/express/ExpressServer.ts

Within Windows WSL, I need to set this to 0.0.0.0 in order to see the port from the browser (in Windows,
when the SDM is running in the linux subsystem)

Use host configuration in Express listen call

---

lib/graph/ApolloGraphClientFactory.ts

The aim of this is to get a name header of `registration/workspace-id` and the version of the automation as the version header.

Add Apollo client identification headers to ApolloGraphClient

---

lib/onCommand.ts
lib/operations/CommandDetails.ts
test/command/onCommand.ts

This PR is in support of https://github.com/atomist/sdm/issues/793.
- For intents, automatically convert from RegExp to strings with the appropriate anchors added (if they are missing)
- Update CommandDetails to allow intents to be RegExp

Enable RegExp for intents
