atomist/automation-client

src/internal/util/commandLine.ts, src/project/git/GitCommandGitProject.ts, src/project/git/GitProject.ts, test/project/git/GitProjectTest.ts
Adds a `clean` function to `GitProject` and convenient types for running commands
=> Added clean function and convenient process types

src/internal/transport/express/ExpressServer.ts, src/server/AbstractAutomationServer.ts, test/command/PlainHelloWorld.ts, test/internal/invoker/BuildableAutomationServerTest.ts
=> use default value of parameters from dashboard

src/action/actionOps.ts, test/action/actionChainingTest.ts, test/operations/edit/projectEditorsOpsTest.ts
This catches errors after each step and wraps them in an editResult.
and adds some tests.
=> catch more errors

src/internal/invoker/Payload.ts, src/internal/metadata/decoratorSupport.ts, src/internal/parameterPopulation.ts, src/metadata/automationMetadata.ts, src/metadata/parameterUtils.ts, src/server/AbstractAutomationServer.ts, src/server/BuildableAutomationServer.ts, test/internal/metadata/classStyleMetadataReadingTest.ts
Fixes #57. Adds support for array parameters.
=> Added array parameters

src/project/git/GitCommandGitProject.ts, test/project/git/GitProjectTest.ts
two tests were both creating the same repository, and it deleted it after each of them.
I got 422 on one of them locally, unless I ran it alone.
After a lot of cleanup, it passes locally with all the tests running.
=> Test cleanup. Now it passes for me locally

src/project/File.ts, src/project/Project.ts, src/project/local/NodeFsLocalFile.ts, src/project/local/NodeFsLocalProject.ts, src/project/mem/InMemoryProject.ts, src/project/support/AbstractFile.ts, src/project/support/AbstractProject.ts, test/project/local/NodeFsLocalFileTest.ts
i need this for the editor I'm working on now.
Opted to implement it async for consistency with the other methods I'm using. 
the isExecutable exists to make the other testable
=> ability to make a file executable

src/operations/edit/editModes.ts, src/operations/edit/projectEditor.ts, src/operations/support/editorUtils.ts, test/operations/edit/editAllTest.ts
my goal here was to test a failed editor, to test the failedEdit convenience function.
which led me to notice that given a custom edit mode, the editor was never called. So I changed that.
=> Better edit tests

test/tree/ast/microgrammar/MicrogrammarBasedFileParserTest.ts
this is to help with: https://github.com/atomist/microgrammar/issues/33#issuecomment-342524265
=> Add a test that demonstrates nesting

src/operations/common/GitHubRepoRef.ts, src/operations/common/RepoId.ts, test/project/git/GitProjectTest.ts
This isn't yet handled in `GitCommandGitProject`, so it isn't observed yet, but putting it up now to avoid merge conflict with @jessitron work.
=> Progress on #97: Allow RepoRef to specify a subdirectory=

package-lock.json, package.json, src/action/cli/commandLine.ts, src/project/Project.ts, src/project/git/GitCommandGitProject.ts, src/project/git/GitProject.ts, src/project/git/gitStatus.ts, src/project/local/LocalProject.ts, src/project/local/NodeFsLocalProject.ts, src/spi/clone/CachingDirectoryManager.ts, src/spi/clone/DirectoryManager.ts, src/spi/clone/StableDirectoryManager.ts, src/spi/clone/tmpDirectoryManager.ts, test-api/ApolloGraphClientTest.ts, test/operations/generate/generatorEndToEndTest.ts, test/project/git/CachedGitCloneTest.ts, test/project/git/GitProjectTest.ts, test/project/git/GitStatusTest.ts, test/project/git/LockfileLibraryTest.ts, test/project/local/NodeFsLocalProjectTest.ts, test/project/utils.ts, test/tree/ast/typescript/typeScriptFileParserProjectTest.ts
I am going to create this and then add comments so I don't lose them again.
=> Cached repos 58

src/project/git/gitStatus.ts, test/project/git/GitStatusTest.ts
@johnsonr see if this works for you?
I don't know how to test it on earlier versions. If it works for you, we can document that we require git 2.10
=> Don't require git v2.13

CHANGELOG.md, package-lock.json, package.json, src/project/File.ts, src/project/local/NodeFsLocalFile.ts, src/project/mem/InMemoryFile.ts, src/project/support/AbstractFile.ts, test/project/local/NodeFsLocalFileTest.ts
Adds `isBinary` method on `File` interface.
=> Fix #90: Adds isBinary to File interface

src/project/git/GitCommandGitProject.ts, test/project/git/CachedGitCloneTest.ts, test/project/git/GitProjectTest.ts
I forgot to make this specific enough, and it failed to check out a branch named "test" because a "test" directory exists.
Fixing it: 3 min. Getting a test to prove that I fixed something: at least an hour. grrr.
=> careful checkout

src/SmartParameters.ts, src/server/BuildableAutomationServer.ts, test/internal/invoker/BuildableAutomationServerTest.ts
This is a more elegant solution than the present use of special regexes.
=> Added SmartParameters interface for optional parameter validation

src/internal/metadata/metadataReading.ts, src/server/BuildableAutomationServer.ts, test/internal/invoker/BuildableAutomationServerTest.ts
Bug fix for nested parameter handling
=> Fixes for nested parameter handling

src/operations/generate/AbstractGenerator.ts, src/operations/generate/generatorUtils.ts, test/project/git/CachedGitCloneTest.ts
because I almost spent time on it, and shouldn't.
this isn't much of a PR but is this comment change ok?
(and removed unused imports)
=> Comment AbstractGenerator as deprecated

src/project/git/GitCommandGitProject.ts, src/spi/clone/DirectoryManager.ts, test/project/git/CachedGitCloneTest.ts
otherwise, you don't know whether you'll get a deep clone or not, once we start using the caching one.
I could cheat and ask for a branch other than master but that's silly, better to be explicit and pass in an option.
=> Allow people to request that a clone be deep

src/HandlerContext.ts, src/internal/invoker/resourceRecovery.ts, src/internal/metadata/metadataReading.ts, src/internal/transport/AbstractRequestProcessor.ts, src/server/BuildableAutomationServer.ts, test/internal/invoker/releaseResourcesTest.ts, test/internal/transport/AbstractRequestProcessorTest.ts
The objective is for the cached directory manager to attach a release step to the context, and have it invoked automatically when the invocation finishes.
=> Release resources

src/tree/ast/FileHits.ts, src/tree/ast/typescript/TypeScriptFileParser.ts, test/tree/ast/astUtilsTest.ts, test/tree/ast/microgrammar/microgrammarsTest.ts
This test illustrates a failure, in updating a tree node and then flushing.
=> Flush doubles the file content

src/operations/common/defaultRepoLoader.ts, src/operations/common/gitHubRepoLoader.ts, src/operations/generate/generatorToCommand.ts, src/operations/generate/generatorUtils.ts
and then release them right after making the copy.
This puts a performance boost where we most want it
=> Cache the seeds

package-lock.json, package.json, src/operations/generate/generatorToCommand.ts, src/operations/generate/generatorUtils.ts, src/operations/generate/support/addAtomistWebhook.ts, test/operations/generate/generatorToCommandTest.ts, test/operations/generate/generatorUtilsTest.ts
Actually call addAtomistWebhook in the generator handler.
=> Wire up addAtomistWebhook

src/decorators.ts
Add the two missing mapped parameters to the MappedParameters class.
=> Add missing mapped parameter

src/project/git/GitCommandGitProject.ts, test/project/git/GitProjectTest.ts
=> Escape double quotes but nothing else

CHANGELOG.md, package-lock.json, package.json
=> Prepare CHANGELOG for 0.5.2

src/operations/edit/projectEditorOps.ts
This would have helped me yesterday
=> Help with error diagnostics

src/operations/common/params/GitHubTargetsParams.ts, src/operations/support/editorUtils.ts, src/project/git/GitCommandGitProject.ts, src/project/git/GitProject.ts, test/api/editorUtilsWithGitHubPullRequestTest.ts, test/project/git/GitProjectTest.ts
This lets a BranchCommit editMode add a commit to a branch that exists.
Rod, do you think this will mess anything up? It does change the default behavior in the case of branch-exists from "fail" to "push to that branch." I don't know of any current cases where that's not good.
=> Create commit on existing branch

src/automationClient.ts
I got an NPE at startup on this one
=> don't require http

src/operations/common/BitBucketServerRepoRef.ts, test/bitbucketserver-api/BitBucketServerGitTest.ts
Added new RepoRef type to support BitBucketServer support.
Included mocked tests for BitBucketServerRepo ref.
=> Adding BitBucketServer support for atomist-client

src/operations/common/params/GitHubSourceRepoParameters.ts, src/operations/common/params/GitHubTargetsParams.ts, src/operations/generate/GitHubRepoCreationParameters.ts
Backward compatible. Tested with `spring-automation` via Slack.
=> GitHub parameters now allow for GHE

src/spi/message/MessageClient.ts
Lost half an hour on a confusing error message when I guessed wrong on what to pass in to buttonForCommand.
Please adjust for accuracy or your preference... or require a more specific type!
/cc @johnsonr
=> Improve the error when we guess the wrong type

CHANGELOG.md, package.json, src/HandlerResult.ts, src/index.ts
Add reduceResults, useful in event handlers.  Add TypeDoc and all
handler result exports to index.ts.
=> Add reduceResults

CHANGELOG.md, src/atomistWebhook.ts, src/index.ts, src/util/retry.ts, test/atomistWebhookTest.ts
Add helper function for posting webhook payloads common to automation
clients.
=> Add Atomist webhook function and types

src/configuration.ts
this will help with diagnosing load errors. I get these a lot.
=> Print the stack when it fails to load

CHANGELOG.md, src/project/git/GitCommandGitProject.ts, test/project/git/GitCommandGitProjectTest.ts
After successfully creating or checking out a branch, set the branch
property on GitCommandGitProject.
Closes #293
=> Set branch after checking out

src/globals.ts, src/internal/graph/graphQL.ts
Delay the construction of a thing that starts a setTimeout that waits and waits.
This way, importing @atomist/automation-client does not cause your tests to hang forever!
=> Now you can import something from automation-client, and your process can still exit!

src/operations/common/GitHubRepoRef.ts, src/operations/generate/generatorUtils.ts, src/operations/generate/remoteGitProjectPersister.ts
=> Pass visibility through to repo creation

src/cli/commands.ts, src/cli/kube.ts, src/start.cli.ts
Add `atomist kube` command that deploys k8vent and k8-automation to
the Kubernetes cluster using `kubectl`.
Closes #310
=> Add command to install kube utilities

src/start.cli.ts
The Atomist CLI has been moved to @atomist/cli.
Closes #315
=> Deprecate atomist CLI

.gitattributes, src/automationClient.ts, src/configuration.ts, src/internal/transport/express/ExpressRequestProcessor.ts, src/internal/transport/express/ExpressServer.ts
- Make it possible to set GraphClient and MessageClient in config
- Harmonize express server options to avoid duplication
=> Open up configuration

src/operations/edit/projectEditor.ts, src/operations/support/editorUtils.ts
so we can see what branch it made
Currently the only way to find out what branch was created is to look at the logs. Or dig around in git, but then you're just guessing.
=> Include editMode in editResult

src/graph/graphQL.ts, src/internal/graph/graphQL.ts, src/spi/graph/GraphClient.ts, test/graph/GraphQLTest.ts, test/graphql/subscription/fooBar.graphql
=> Use name to lookup graphql by operation name

src/project/Project.ts, src/project/support/AbstractProject.ts, test/project/mem/InMemoryProjectTest.ts
=> Add hasFile method to Project

src/operations/common/params/GitHubTargetsParams.ts
previously, it was populating the sha with the branch and the branch with nothing.
Now, it will populate one or the other, depending which you give it. 
This is necessary for resetGoals to find the push; it needs both the branch and the sha. The TargetRepo parameters infra gives it the branch; resetGoals looks up the sha. (that's in sdm-core. this one is a prereq for that to work, although not to build)
=> Populate the branch or sha on GitHubRepoRef

src/project/util/diagnosticUtils.ts, src/project/util/parseUtils.ts, src/project/util/projectUtils.ts, src/tree/ast/astUtils.ts, test/project/util/projectUtilsTest.ts, test/tree/ast/astUtilsTest.ts
- Add `saveFromMatches` in `astUtils`
- Deprecate `saveFromFilesAsync`
=> Project utils update

src/project/git/GitCommandGitProject.ts, src/project/git/gitStatus.ts, src/spi/clone/DirectoryManager.ts, test/project/git/CachedGitCloneTest.ts
=> Retire cloneBranch

index.ts, test/internal/metadata/eventMetadataReadingTest.ts
Add elements imported by packages that depend on automation-client to
the index.  Organize all the exports.
=> Augment and organize export in index

index.ts
Analyzing various projects turned a few missing exports.
=> Add more exports to index

lib/operations/common/repoUtils.ts
In order to prevent potentially hundreds or thousand of concurrent edit operations, this PR introduces the concept of chunking them into smaller batches. The batch size defaults to 5 but can be globally overwritten.
=> Chunk editAll operations

lib/server/AbstractAutomationServer.ts
=> Explicitly validate parameter values

index.ts, lib/SmartParameters.ts
This introduces an index signature to prevent non-primitive values in parameter objects.
=> Stronger typing for parameters

lib/project/mem/InMemoryProject.ts, test/operations/common/fromProjectList.test.ts
I know we did this at one point, but maybe we lost that branch
=> Provide a dummy id to InMemoryProject

lib/tree/ast/microgrammar/MicrogrammarBasedFileParser.ts, test/tree/ast/microgrammar/microgrammars.test.ts
=> Correct typing on microgrammar matches exposed via path expressions

lib/operations/generate/generatorUtils.ts
... although, why return Promise.reject instead of throwing here?
=> Do not throw a string

lib/operations/generate/NewRepoCreationParameters.ts
This will help in Getting Started
=> Clearer description for generated repo name

lib/internal/parameterPopulation.ts, lib/internal/transport/RequestProcessor.ts, lib/spi/message/MessageClientSupport.ts
and a couple of other smaller enhancements.
=> Add web identity and identity to source map

lib/internal/message/ConsoleMessageClient.ts, lib/internal/message/DebugMessageClient.ts, lib/internal/transport/AbstractRequestProcessor.ts, lib/internal/transport/cluster/ClusterWorkerRequestProcessor.ts, lib/internal/transport/express/ExpressRequestProcessor.ts, lib/internal/transport/websocket/WebSocketMessageClient.ts, lib/internal/transport/websocket/payloads.ts, lib/metadata/automationMetadata.ts, lib/onCommand.ts, lib/spi/message/MessageClient.ts, lib/spi/message/MessageClientSupport.ts, test/command/HelloWorld.ts
This PR adds support for message deletion via new method `MessageClient.delete` and support for declaring the parameter prompt style; eg. _dialog_ or _threaded_.
=> Improvements to message sending protocol

lib/internal/transport/cluster/ClusterMasterRequestProcessor.ts
Separate shutdown initiated behavior from replacing workers behavior
because shutdown can be initiated before you want to not replace
workers, e.g., when shutdown has been initiated but the work queue is
not empty.
Have the master send itself SIGTERM rather than call process.exit so
async shutdown hooks can execute properly.
Towards #543
=> Improve cluster shutdown behavior

lib/operations/common/BitBucketServerRepoRef.ts, package-lock.json, test/operations/common/BitBucketServerRepoRef.test.ts
[atomist:generated] [atomist:autofix=npm_package_lock]
=> Add default reviewer mechanism for BitBucket

lib/project/git/GitCommandGitProject.ts
The previous code produced an error in my testing.
See https://help.github.com/en/articles/adding-a-remote
=> Change git remote set origin to get remote set-url origin. 

lib/configuration.ts, test/util/redact.test.ts
=> Modify GitHub token pattern to match on app tokens

package.json
Apply target `npm-project-deps::lodash`:
_NPM dependencies_
```lodash > ^4.17.15```
---
<details>
<summary>Tags</summary>
<br/>
<code>[atomist:generated]</code><br/><code>[auto-branch-delete:on-close]</code><br/><code>[auto-merge-method:squash]</code><br/><code>[auto-merge:on-approve]</code><br/><code>[fingerprint:npm-project-deps::lodash=67e0a6b0cd3b8a665eef8a872abba84502cced775efba0711ee6e1a3ba51698b]</code>
</details>
=> Apply target for lodash

bin/gql-gen.ts
Do not create typings directory if not creating types from GraphQL.
=> Do not create typings dir if not creating types

index.ts
Add isTokenCredentials and isGitHubRepoRef exports to index.
=> Add exports to index

lib/operations/common/AbstractRemoteRepoRef.ts, lib/operations/common/BitBucketRepoRef.ts, lib/operations/common/BitBucketServerRepoRef.ts, lib/operations/common/GitHubRepoRef.ts, lib/operations/common/GitlabRepoRef.ts, lib/operations/common/RepoId.ts, lib/operations/edit/editModes.ts, lib/operations/support/editorUtils.ts, lib/project/git/GitCommandGitProject.ts, lib/project/git/GitProject.ts, test/api/GitProjectRemote.test.ts, test/api/editorUtilsWithGitHubPullRequest.test.ts, test/bitbucket-api/BitBucketGit.test.ts, test/operations/common/BitBucketServerRepoRef.test.ts, test/operations/common/GitHubRepoRef.test.ts, test/operations/common/GitlabRepoRef.test.ts
Closes #531
* Updated interfaces and Abstract class for reporef
* Update edit modes
* Update Github Repo Ref
* Update Bitbucket Repo Ref
* Update Gitlab Repo Ref
* Created/Updated tests for RepoRef raise pull request with reviewers
* Replaced direct axios usage with HttpClient in GIthub Repo Ref
=> Support adding reviewers to PRs on Creation

lib/configuration.ts
The previous code wasn't working on Windows which this change fixes.
=> Fix globbing of client config
